server:
  address: 127.0.0.10
  port : 9090

management:
   endpoints:
      web:
         exposure:
            include: refresh
      health:
         show-details: always
   health:
      circuitbreakers:
         enabled: true
         
eureka:
   client:
      service-url:
         defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
   instance:
         instance-id: ${spring.application.name}:${random.uuid}
         
spring:
   zipkin:
      base-url:  http://127.0.0.2:9411
   sleuth:
      reactor:
         instrumentation-type: decorate-on-each

   cloud:
        gateway:
            discovery:
               locator:
                  enabled: true
                  lower-case-service-id: true