server:
  port: 0
  
management:
   endpoints:
      web:
         exposure:
            include: refresh
      health:
         show-details: always
   health:
      circuitbreakers:
         enabled: false
               
eureka:
   client:
      service-url:
         defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
   instance:
      instance-id: ${spring.application.name}:${random.uuid}
      
spring:
  main:
    allow-bean-definition-overriding: true
  mail:
      host: smtp.gmail.com
      port: 465
      protocol: smtps
      username: oabdennour@gmail.com
      password: xxxxxxxxxxxxxxxxxxxx
      properties:
        mail:
          transport:
            protocol: smtps
          smtps:
            auth: true
            starttls:
              enable: true
              timeout: 8000
  data:
    rest:
      defaultMediaType: application/json
  zipkin:
    base-url:  http://localhost:9411
  jpa:
    defer-datasource-initialization: true
  datasource:
    initialization-mode: always
    driverClassName: org.mariadb.jdbc.Driver
    platform: mariadb
    url: jdbc:mariadb://localhost:3306/login_registration_db
    username: root
    password: 123456
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
#      settings:
#        trace: false
#        web-allow-others: false
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    show-sql: false
  profiles:
    active: dev
    
file:
  upload_dir: ${upload-dir:/home/omar/Documents/zibra-upload}

jwt:
  token:
    expiration:
      in:
        seconds: 86400000
  secretKey : mysecret
  signing:
    key:
      secret: 15656fae13awAWEe5ewaf
app:
  jwtSecret: bezKoderSecretKey
  jwtExpirationMs: 86400000
    
################### geoip2 Configuration ##########################   
geo:
  ip:
    lib:
      enabled: false
################### cron Configuration ########################## 
purge:
  cron:
    expression: 0 0 5 * * ?
################### JavaMail Configuration ##########################
support:
  email: USERNAME@gmail.com

  
      