server:
  port: 0
  
management:
   endpoints:
      web:
         exposure:
            include: refresh
      health:
         show-details: always
   health:
      circuitbreakers:
         enabled: true
         
         
eureka:
   client:
      service-url:
         defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
   instance:
      instance-id: ${spring.application.name}:${random.uuid}
spring:
  zipkin:
    base-url:  http://127.0.0.2:9411
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    platform: mariadb
    url: jdbc:mariadb://127.0.0.2:3306/marketing-db
    username: root
    password: 123456
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
#      settings:
#        trace: false
#        web-allow-others: false
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create-drop
    show-sql: false
  profiles:
    active: dev