server:
  port: 0
  
management:
   endpoints:
      web:
         exposure:
            include: refresh
      health:
         show-details: always
   health:
      circuitbreakers:
         enabled: false
               
eureka:
   client:
      service-url:
         defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
   instance:
      instance-id: ${spring.application.name}:${random.uuid}
spring:
  data:
    rest:
      defaultMediaType: application/json
      #base-path: /api
  #zipkin:
    #base-url:  http://localhost:9411
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    platform: mysql
    url: jdbc:mysql://localhost:3306/zibra_marketing_db?createDatabaseIfNotExist=true
    username: root
    password: 123456
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
#      settings:
#        trace: false
#        web-allow-others: false
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create-drop   #none #drop #create #create-only #create-drop #update #validate
    show-sql: false
  profiles:
    active: dev