server:
  port: 0
  
management:
   endpoints:
      web:
         exposure:
             include: healt
      health:
         show-details: always
      routes:
        enabled: true
   health:
      circuitbreakers:
         enabled: false
               
eureka:
   client:
      service-url:
         defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
   instance:
      instance-id: ${spring.application.name}:${random.uuid}
spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB
  data:
    rest:
      defaultMediaType: application/json
  zipkin:
    base-url:  http://localhost:9411
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    platform: mariadb
    url: jdbc:mariadb://localhost:3306/db
    username: root
    password: 123456
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
#      settings:
#        trace: false
#        web-allow-others: false
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    show-sql: false
  profiles:
    active: dev
    
file:
  upload_dir: ${upload-dir:/home/omar/Documents/zibra-upload}
  
admin:
  username: superadmin
  fullName: superadmin
  password: superadmin
  status: Y
  emailAddress: superadmin@f1soft.com
  loginAttempt: 0
  profileId : 1
  
jwt:
  secretKey: mysecret
  validityInMilliseconds: 3600000
      